import * as T from 'three';
import {PointerLockControls} from 'three/addons/controls/PointerLockControls.js';
const scene=new T.Scene();scene.background=new T.Color(0x819ba7);scene.fog=new T.Fog(0x819ba7,35,95);
const camera=new T.PerspectiveCamera(75,innerWidth/innerHeight,.05,150);scene.add(camera);
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;document.body.append(renderer.domElement);
scene.add(new T.HemisphereLight(0xe5f6ff,0x544739,2));const sun=new T.DirectionalLight(0xffe4bc,2);sun.position.set(12,35,10);sun.castShadow=true;sun.shadow.camera.left=-35;sun.shadow.camera.right=35;sun.shadow.camera.top=35;sun.shadow.camera.bottom=-35;sun.shadow.mapSize.set(1024,1024);scene.add(sun);
const controls=new PointerLockControls(camera,document.body),clock=new T.Clock(),ray=new T.Raycaster(),keys={},walls=[],bots=[];const hud=document.querySelector('#hud'),button=document.querySelector('#start');
function mesh(w,h,d,color,parent=scene){const m=new T.Mesh(new T.BoxGeometry(w,h,d),new T.MeshStandardMaterial({color,roughness:.7}));m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function wall(x,z,w,h,d,c=0x9a876e){const m=mesh(w,h,d,c);m.position.set(x,h/2,z);walls.push(m);}
mesh(70,.2,70,0x686854).position.y=-.1;wall(0,-30,60,7,2);wall(0,30,60,7,2);wall(-30,0,2,7,60);wall(30,0,2,7,60);
for(const [x,z,w,d] of [[-10,-8,8,5],[10,8,8,5],[-18,14,5,7],[17,-15,6,5],[0,-17,4,4],[0,17,4,4]])wall(x,z,w,3,d,0x776a55);
for(let x=-24;x<=24;x+=8){const m=mesh(1,1,.15,0x3b5363);m.position.set(x,4,-28.9);}
const gun=new T.Group();camera.add(gun);const receiver=mesh(.13,.15,.5,0x26313b,gun);receiver.position.z=-.14;const barrel=mesh(.045,.045,.4,0x172027,gun);barrel.position.set(0,.02,-.54);mesh(.085,.23,.12,0x222a30,gun).position.set(0,-.12,-.13);mesh(.09,.2,.1,0x323a42,gun).position.set(0,-.15,-.32);for(const x of [-.1,.13])mesh(.1,.1,.35,0xc99d7e,gun).position.set(x,-.12,.08);const flash=mesh(.13,.13,.1,0xffbf40,gun);flash.material=new T.MeshBasicMaterial({color:0xffd25a});flash.position.z=-.77;flash.visible=false;
let hp,ammo,reserve,reloading=0,fireDelay=0,recoil=0,vertical=0,shooting=false,round=0,wins=0,losses=0,time=0,phase='ready',audio;
function sound(freq,duration=.08){if(!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type='sawtooth';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(40,audio.currentTime+duration);g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}
function human(x,z){const root=new T.Group();root.position.set(x,0,z);scene.add(root);const parts=[];function part(w,h,d,c,px,py,pz){const m=mesh(w,h,d,c,root);m.position.set(px,py,pz);parts.push(m);return m;}part(.55,.65,.3,0x8e3b34,0,1.15,0);part(.28,.3,.27,0xd0a37f,0,1.65,0);part(.32,.13,.3,0x303a43,0,1.83,0);const legs=[part(.19,.65,.22,0x303a43,-.16,.4,0),part(.19,.65,.22,0x303a43,.16,.4,0)];part(.15,.5,.17,0x8e3b34,-.35,1.07,0);part(.15,.5,.17,0x8e3b34,.35,1.07,0);part(.12,.12,.65,0x222a30,.25,1.1,.25);const b={root,parts,legs,hp:100,cd:1+Math.random(),angle:Math.random()*6};for(const p of parts)p.userData.bot=b;bots.push(b);}
function startRound(){for(const b of bots)scene.remove(b.root);bots.length=0;hp=100;ammo=30;reserve=120;round++;time=100;vertical=0;reloading=0;shooting=false;recoil=0;fireDelay=0;camera.position.set(0,1.7,24);for(const [x,z] of [[-23,-23],[-4,-24],[22,-23],[24,0]])human(x,z);phase='live';}
function blocked(x,z){return walls.some(w=>Math.abs(x-w.position.x)<w.geometry.parameters.width/2+.35&&Math.abs(z-w.position.z)<w.geometry.parameters.depth/2+.35);}
function move(p,dx,dz){if(!blocked(p.x+dx,p.z))p.x+=dx;if(!blocked(p.x,p.z+dz))p.z+=dz;}
function finish(win){phase='over';shooting=false;if(win)wins++;else losses++;button.textContent=win?'Победа — следующий раунд':'Поражение — новый раунд';controls.unlock();}
button.onclick=()=>{if(!audio){const Audio=window.AudioContext||window.webkitAudioContext;if(Audio)audio=new Audio();}audio?.resume();if(phase!=='live')startRound();controls.lock();};controls.addEventListener('lock',()=>button.hidden=true);controls.addEventListener('unlock',()=>{button.hidden=false;shooting=false;for(const k in keys)keys[k]=false;});
addEventListener('keydown',e=>{if(['Space','KeyW','KeyS','KeyA','KeyD'].includes(e.code))e.preventDefault();keys[e.code]=true;if(e.code==='KeyR'&&controls.isLocked&&phase==='live'&&!reloading&&ammo<30&&reserve){reloading=1.4;sound(150,.15);}});addEventListener('keyup',e=>keys[e.code]=false);addEventListener('mousedown',e=>{if(e.button===0&&controls.isLocked)shooting=true;});addEventListener('mouseup',()=>shooting=false);addEventListener('blur',()=>{shooting=false;for(const k in keys)keys[k]=false;});
function fire(){if(fireDelay>0||reloading||!ammo)return;ammo--;fireDelay=.11;recoil=.075;flash.visible=true;sound(100,.07);ray.setFromCamera(new T.Vector2((Math.random()-.5)*.012,(Math.random()-.5)*.012),camera);const hits=ray.intersectObjects([...walls,...bots.flatMap(b=>b.parts)],false),hit=hits[0],b=hit?.object.userData.bot;if(b){b.hp-=hit.point.y>1.5?100:34;document.querySelector('#aim').style.color='#ff5252';if(b.hp<=0){scene.remove(b.root);bots.splice(bots.indexOf(b),1);}}camera.rotateX(.006);}
function frame(){requestAnimationFrame(frame);const dt=Math.min(clock.getDelta(),.04);if(phase==='live'&&controls.isLocked){time-=dt;fireDelay=Math.max(0,fireDelay-dt);if(reloading){reloading=Math.max(0,reloading-dt);if(!reloading){const n=Math.min(30-ammo,reserve);ammo+=n;reserve-=n;}}const direction=new T.Vector3();camera.getWorldDirection(direction);direction.y=0;direction.normalize();const right=new T.Vector3().crossVectors(direction,camera.up);const f=(keys.KeyW?1:0)-(keys.KeyS?1:0),r=(keys.KeyD?1:0)-(keys.KeyA?1:0),length=Math.hypot(f,r)||1,s=(keys.ShiftLeft?7:4.5)*dt/length;move(camera.position,(direction.x*f+right.x*r)*s,(direction.z*f+right.z*r)*s);if(keys.Space&&camera.position.y<=1.701)vertical=5;vertical-=14*dt;camera.position.y+=vertical*dt;if(camera.position.y<1.7){camera.position.y=1.7;vertical=0;}if(shooting)fire();for(const b of bots){const d=camera.position.clone().sub(b.root.position);d.y=0;const distance=d.length();d.normalize();b.root.rotation.y=Math.atan2(d.x,d.z);if(distance>7){const old=b.root.position.clone();move(b.root.position,d.x*dt*1.5,d.z*dt*1.5);if(old.distanceToSquared(b.root.position)<.00001)move(b.root.position,Math.cos(b.angle)*dt*2,Math.sin(b.angle)*dt*2);b.angle+=dt*.4;}b.legs[0].rotation.x=Math.sin(clock.elapsedTime*7)*.25;b.legs[1].rotation.x=-b.legs[0].rotation.x;b.cd-=dt;if(distance<24&&b.cd<=0){b.cd=.8+Math.random()*.6;const eye=b.root.position.clone().add(new T.Vector3(0,1.5,0)),target=camera.position.clone().sub(eye),len=target.length();ray.set(eye,target.normalize());const cover=ray.intersectObjects(walls,false)[0];if(!cover||cover.distance>len){hp-=7;sound(65);}}}if(hp<=0||time<=0)finish(false);else if(!bots.length)finish(true);}recoil=Math.max(0,recoil-dt*.5);flash.visible=fireDelay>.075&&controls.isLocked;gun.position.set(.23,-.23-reloading*.08,-.42+recoil);gun.rotation.z=reloading?-.4:0;gun.rotation.x=-recoil;hud.textContent=`STRIKEZONE | Раунд ${round} | Счёт ${wins}:${losses} | ${Math.ceil(Math.max(0,time))}с | HP ${Math.max(0,hp||0)} | ${ammo||0}/${reserve||0} | Боты ${bots.length} | ${reloading?'Перезарядка':'WASD · ЛКМ · R · Space · Shift'}`;if(fireDelay<=0)document.querySelector('#aim').style.color='white';renderer.render(scene,camera);}frame();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
